# Generated by Django 5.2.6 on 2025-10-20 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('proveedor', 'Proveedor'), ('cliente', 'Cliente'), ('empleado', 'Empleado')], max_length=10),
        ),
    ]
