# Generated by Django 5.2.6 on 2025-10-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='temporal',
            field=models.BooleanField(default=True),
        ),
    ]
