# Generated by Django 5.2.6 on 2025-11-15 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("task", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clientes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="empleados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="facturaventa",
            name="id_cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="facturas",
                to="task.cliente",
            ),
        ),
        migrations.AddField(
            model_name="facturaventa",
            name="id_empleado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="facturas",
                to="task.empleado",
            ),
        ),
        migrations.AddField(
            model_name="detalleventa",
            name="id_factura",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalles",
                to="task.facturaventa",
            ),
        ),
        migrations.AddField(
            model_name="movimiento",
            name="id_cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movimiento",
                to="task.cliente",
            ),
        ),
        migrations.AddField(
            model_name="movimiento",
            name="responsable",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movimientos",
                to="task.empleado",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="id_categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productos",
                to="task.categoria",
            ),
        ),
        migrations.AddField(
            model_name="movimiento",
            name="id_producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movimiento",
                to="task.producto",
            ),
        ),
        migrations.AddField(
            model_name="detalleventa",
            name="id_producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalles",
                to="task.producto",
            ),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proveedores",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="id_proveedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productos_proveedor",
                to="task.proveedor",
            ),
        ),
        migrations.AddField(
            model_name="movimiento",
            name="id_proveedor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movimiento",
                to="task.proveedor",
            ),
        ),
    ]
