# Generated by Django 5.2.6 on 2025-10-18 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_categoria_temporal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='nombre',
        ),
        migrations.AddField(
            model_name='categoria',
            name='nom',
            field=models.CharField(default='general', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
