# Generated by Django 5.2.6 on 2025-10-18 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_remove_categoria_nombre_categoria_nom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nom',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='temporal',
        ),
    ]
