# Generated by Django 5.2.6 on 2025-10-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_rename_contacto_proveedor_telefono_cliente_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='created',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='created',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='telefono',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='contacto',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
