# Generated by Django 5.2.6 on 2025-10-22 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_cliente_created_cliente_modified_empleado_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='cargo',
        ),
    ]
